language: go

go:
  - 1.7.3

branches:
  only:
    - source

env:
 global:
   - GH_REF: github.com/mzvast/mzvast.github.io.git

sudo: required

git:
  submodules: false

# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

install:
  - sudo pip install Pygments
  - wget https://github.com/spf13/hugo/releases/download/v0.17/hugo_0.17_Linux-64bit.tar.gz
  - tar xzf hugo_0.17_Linux-64bit.tar.gz
  - mv hugo_0.17_linux_amd64/hugo_0.17_linux_amd64 hugo
  - chmod a+x hugo

script:
  - ./hugo

after_script:
  - cd ./public
  - git init
  - git config user.name "mzvast"
  - git config user.email "mzvast@gmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master